export function normalizeContributorLastName(name) {
    if (name.includes('AT&T')) return 'AT&T'
    if (name.includes('California Apartment Association')) return 'California Apartment Association'
    if (name.includes('California Correctional Peace Officers Association Political Action Committee')) return 'California Correctional Peace Officers Association'
    if (name.includes('CCPOA Local PAC')) return 'California Correctional Peace Officers Association'
    if (name.includes('California Association Of Realtors')) return 'California Association Of Realtors'
    if (name.includes('CREPAC')) return 'California Association of Realtors'
    if (name.includes('California Real Estate Political Action Committee')) return 'California Association of Realtors'
    if (name.includes('California Nurses Association')) return 'California Nurses Association'
    if (name.includes('Electrical Workers Local 340')) return 'International Brotherhood of Electrical Workers Local 340'
    if (name.includes('Pipefitters Local Union 447')) return 'Plumbers & Pipefitters Local Union 447'
    if (name.includes('Pipefitters Local Union No. 447')) return 'Plumbers & Pipefitters Local Union 447'
    if (name.includes('Plumbers & Pipefitters Local 447 Federal PAC')) return 'Plumbers & Pipefitters Local Union 447'
    if (name.includes('Sacramento Area Fire Fighters Local 522')) return 'Sacramento Area Fire Fighters Local 522'
    if (name.includes('Sacramento Area Firefighters Local 522 PAC')) return 'Sacramento Area Fire Fighters Local 522'
    if (name.includes('Sacramento Area Firefighters (SAFF) Local 522')) return 'Sacramento Area Fire Fighters Local 522'
    if (name.includes('Sacramento City Teachers Association')) return 'Sacramento City Teachers Association'
    if (name.includes('Sac City Teachers Association')) return 'Sacramento City Teachers Association'
    if (name.includes('Sacramento County Deputy Sheriffs Association')) return 'Sacramento County Deputy Sheriffs Association'
    if (name.includes('Sacramento Police Officers Association')) return 'Sacramento Police Officers Association'
    if (name.includes('Charter Public Schools PAC')) return 'California Charter Schools Association'
    if (name.includes('SEIU') && name.includes('1000')) return 'Service Employees International Union Local 1000'
    if (name.includes('Service Employees International Union Local 1000')) return 'Service Employees International Union Local 1000'
    return name
}